FROM elixir:1.5.0

MAINTAINER Carlos André (carlos.ulrich@gmail.com)

ENV REFRESHED_AT 2017-07-29

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix deps.get

CMD ["bash"]
