FROM bitwalker/alpine-erlang:19.3

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

ENV MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD elixir_crawler.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/elixir_crawler"]
